#!/bin/bash
sessions=$(tmux list-sessions -F '#{session_name}')
current_session=$(tmux display-message -p '#S')
formatted_sessions=""
for session in $sessions; do
    if [ "$session" = "$current_session" ]; then
        formatted_sessions+="#[fg=magenta,bold]$session "
    else
        formatted_sessions+="#[fg=blue,nobold]$session "
    fi
done
echo -n "${formatted_sessions%}"
